name: mne3
channels:
  - defaults
dependencies:
  - autopep8
  - scikit-learn
  - pytest-mock
  - traits
  - gevent
  - tensorboard
  - pip
  - xlrd
  - conda-forge::pyod
  - numexpr
  - cython
  - lxml
  - seaborn
  - mkl
  - pyqt
  - altair
  - pytest
  - testpath
  - numpy
  - pandas
  - flake8
  - statsmodels
  - python[version='<3.7']
  - conda-forge::peakutils
  - matplotlib
  - joblib
  - conda-forge::umap-learn
  - scipy
  - rigge::peak-detect
  - vega_datasets
  - pyface
  - traitsui
  - jupyter
  - pytest-timeout
  - pytest-cov
  - numpydoc
  - spyder
  - psutil
  - opencv
  - plotly
  - h5py
  - pillow
prefix: /anaconda2/envs/mne3

