name: mne3
channels:
  - rigge
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py36_0
  - altair=4.0.1=py_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astroid=2.2.5=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - babel=2.7.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.12.3=py36hb5b8e2f_0
  - chardet=3.0.4=py36_1003
  - chisel=snapshot=3
  - cloudpickle=1.2.2=py_0
  - coverage=4.5.3=py36h1de35cc_0
  - cryptography=2.7=py36ha12b0ac_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.29.13=py36h0a44026_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - ffmpeg=4.0=h01ea3c9_0
  - flake8=3.7.7=py36_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - gevent=1.4.0=py36h0b31af3_0
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.13=h2098e52_0
  - greenlet=0.4.15=py36h0b31af3_0
  - h5py=2.8.0=py36h878fce3_3
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - idna=2.8=py36_0
  - imagesize=1.1.0=py36_0
  - importlib_metadata=0.19=py36_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.2=py36_0
  - junit=4.12=0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.5.0=py_0
  - keyring=18.0.0=py36_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - lazy-object-proxy=1.4.2=py36h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.10=hcb84e12_2
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hf6e021a_1
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvmlite=0.29.0=py36h3fea490_1
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.1=py36h54f8f79_0
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.14=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - more-itertools=7.2.0=py36_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py36_0
  - numba=0.45.1=py36h86efe34_0
  - numexpr=2.7.0=py36h7413580_0
  - numpy=1.16.5=py36hacdab7b_0
  - numpy-base=1.16.5=py36h6575580_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1f=h0b31af3_0
  - packaging=19.1=py36_0
  - pandas=0.25.1=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=h0a44026_0
  - peak-detect=0.1=5
  - peakutils=1.3.3=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36hb68e598_0
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h1de35cc_0
  - plotly=4.4.1=py_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.3=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - py-opencv=3.4.2=py36h7c891bd_1
  - pycodestyle=2.5.0=py36_0
  - pycparser=2.19=py36_0
  - pyface=6.1.2=py36_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.14.11=py36h1de35cc_0
  - pysocks=1.7.0=py36_0
  - pytest=5.0.1=py36_0
  - pytest-cov=2.7.1=py_0
  - pytest-mock=1.10.4=py36_0
  - pytest-timeout=1.3.3=py36_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.0=py36_0
  - python.app=2=py36_9
  - python_abi=3.6=1_cp36m
  - pytz=2019.2=py_0
  - pyzmq=18.1.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.5.7=py36_1
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py36_0
  - retrying=1.3.3=py36_2
  - rope=0.14.0=py_0
  - scala=2.10.4=0
  - scikit-learn=0.21.2=py36h27c97d8_0
  - scipy=1.3.1=py36h1410ff5_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.12.0=py36_0
  - snowballstemmer=1.9.0=py_0
  - sphinx=2.1.2=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.6=py36_0
  - spyder-kernels=0.5.1=py36_0
  - sqlite=3.29.0=ha441bb4_0
  - statsmodels=0.10.1=py36h1d22016_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - traits=5.1.1=py36h1de35cc_0
  - traitsui=6.1.2=py_0
  - typed-ast=1.3.4=py36h1de35cc_0
  - umap-learn=0.3.10=py36_0
  - urllib3=1.24.2=py36_0
  - vega_datasets=0.8.0=py_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h1de35cc_0
  - wurlitzer=1.0.3=py36_0
  - xlrd=1.2.0=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.5.2=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - appdirs==1.4.3
    - apptools==4.4.0
    - bokeh==1.2.0
    - codespell==1.15.0
    - configobj==5.0.6
    - dipy==0.16.0
    - envisage==4.7.2
    - imageio==2.5.0
    - markdown==3.1.1
    - mayavi==4.7.0.dev0
    - mne==0.18.1
    - neo==0.7.1
    - nibabel==2.4.1
    - nilearn==0.5.2
    - panel==0.6.0
    - param==1.9.1
    - peakdetect==1.1
    - pyct==0.4.6
    - pydocstyle==3.0.0
    - pyedflib==0.1.15
    - pylsl==1.13.1
    - pysurfer==0.9.0
    - pytest-faulthandler==1.6.0
    - pytest-sugar==0.9.2
    - python-picard==0.4
    - pyvista==0.20.3
    - pyviz-comms==0.7.2
    - pyyaml==5.1.1
    - quantities==0.12.3
    - termcolor==1.1.0
    - vtk==8.1.2
    - wonambi==6.8
prefix: /anaconda2/envs/mne3

